In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_excel('C:/Users/vaibh/OneDrive/Desktop/Starttech_Task/Data_file.xlsx',header=0)

In [3]:
df.head()

S.No. College       Role  City type  Previous CTC  Previous job changes  \
0      1  Tier 1    Manager  Non-Metro         55523                     3   
1      2  Tier 2  Executive      Metro         57081                     1   
2      3  Tier 2  Executive      Metro         60347                     2   
3      4  Tier 3  Executive      Metro         49010                     2   
4      5  Tier 3  Executive      Metro         57879                     4   

   Graduation marks  Exp (Months)           CTC  
0                66            19  71406.576531  
1                84            18  68005.870631  
2                52            28  76764.020277  
3                81            33  82092.386880  
4                74            32  73878.097729

In [4]:
df.shape

(1338, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   S.No.                 1338 non-null   int64  
 1   College               1338 non-null   object 
 2   Role                  1338 non-null   object 
 3   City type             1338 non-null   object 
 4   Previous CTC          1338 non-null   int64  
 5   Previous job changes  1338 non-null   int64  
 6   Graduation marks      1338 non-null   int64  
 7   Exp (Months)          1338 non-null   int64  
 8   CTC                   1338 non-null   float64
dtypes: float64(1), int64(5), object(3)
memory usage: 94.2+ KB


### There is no missing Value in the dataset.

In [6]:
df.describe()

S.No.  Previous CTC  Previous job changes  Graduation marks  \
count  1338.000000   1338.000000           1338.000000       1338.000000   
mean    669.500000  55581.762332              2.525411         59.890882   
std     386.391641   6685.600553              1.123502         14.894696   
min       1.000000  36990.000000              1.000000         35.000000   
25%     335.250000  50547.000000              2.000000         47.000000   
50%     669.500000  55293.500000              3.000000         60.000000   
75%    1003.750000  60150.500000              4.000000         73.000000   
max    1338.000000  77911.000000              4.000000         85.000000   

       Exp (Months)            CTC  
count   1338.000000    1338.000000  
mean      39.207025   75459.338993  
std       14.049960   12551.280263  
min       18.000000   53020.319026  
25%       27.000000   66905.070033  
50%       39.000000   73112.640487  
75%       51.000000   80747.178420  
max       64.000000  123416.994271

### No outliers in the Dataset

# Creating Linear Regression Model

### Method 1 : Using Sklearn Model

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
lm = LinearRegression()

In [9]:
df.head()

S.No. College       Role  City type  Previous CTC  Previous job changes  \
0      1  Tier 1    Manager  Non-Metro         55523                     3   
1      2  Tier 2  Executive      Metro         57081                     1   
2      3  Tier 2  Executive      Metro         60347                     2   
3      4  Tier 3  Executive      Metro         49010                     2   
4      5  Tier 3  Executive      Metro         57879                     4   

   Graduation marks  Exp (Months)           CTC  
0                66            19  71406.576531  
1                84            18  68005.870631  
2                52            28  76764.020277  
3                81            33  82092.386880  
4                74            32  73878.097729

In [10]:
df = pd.get_dummies(df)

In [11]:
df.head()

S.No.  Previous CTC  Previous job changes  Graduation marks  Exp (Months)  \
0      1         55523                     3                66            19   
1      2         57081                     1                84            18   
2      3         60347                     2                52            28   
3      4         49010                     2                81            33   
4      5         57879                     4                74            32   

            CTC  College_Tier 1  College_Tier 2  College_Tier 3  \
0  71406.576531               1               0               0   
1  68005.870631               0               1               0   
2  76764.020277               0               1               0   
3  82092.386880               0               0               1   
4  73878.097729               0               0               1   

   Role_Executive  Role_Manager  City type_Metro  City type_Non-Metro  
0               0             1                0                    1  
1               1             0                1                    0  
2               1             0                1                    0  
3               1             0                1                    0  
4               1             0                1                    0

In [12]:
del df['College_Tier 3']

In [13]:
del df['Role_Executive']

In [14]:
del df['City type_Non-Metro']

In [15]:
df.head()

S.No.  Previous CTC  Previous job changes  Graduation marks  Exp (Months)  \
0      1         55523                     3                66            19   
1      2         57081                     1                84            18   
2      3         60347                     2                52            28   
3      4         49010                     2                81            33   
4      5         57879                     4                74            32   

            CTC  College_Tier 1  College_Tier 2  Role_Manager  City type_Metro  
0  71406.576531               1               0             1                0  
1  68005.870631               0               1             0                1  
2  76764.020277               0               1             0                1  
3  82092.386880               0               0             0                1  
4  73878.097729               0               0             0                1

# X-y split

In [16]:
X = df.drop('CTC',axis=1)

In [17]:
y = df['CTC']

In [18]:
X.head()

S.No.  Previous CTC  Previous job changes  Graduation marks  Exp (Months)  \
0      1         55523                     3                66            19   
1      2         57081                     1                84            18   
2      3         60347                     2                52            28   
3      4         49010                     2                81            33   
4      5         57879                     4                74            32   

   College_Tier 1  College_Tier 2  Role_Manager  City type_Metro  
0               1               0             1                0  
1               0               1             0                1  
2               0               1             0                1  
3               0               0             0                1  
4               0               0             0                1

In [19]:
y.head()

0    71406.576531
1    68005.870631
2    76764.020277
3    82092.386880
4    73878.097729
Name: CTC, dtype: float64

# Test Train Split

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [22]:
X_train.shape

(1070, 9)

In [23]:
y_train.shape

(1070,)

In [24]:
lm.fit(X_train,y_train)

LinearRegression()

# Model Prediction

In [25]:
y_train_predicted = lm.predict(X_train)

In [26]:
y_train_predicted

array([94648.40559188, 68719.98692989, 88520.25527041, ...,
       69396.70523182, 67172.83928757, 63617.3505221 ])

In [27]:
y_test_predicted = lm.predict(X_test)

In [28]:
y_test_predicted

array([ 79340.05788044,  69069.68397878,  97124.97714335,  79017.77539717,
        65375.38336947,  72213.97301376,  64087.6569129 ,  72138.17617583,
        67273.19908662,  71849.86727597,  63805.74722433,  67659.73887272,
        70484.36188941,  60128.97395109,  85062.92798344,  66532.14459661,
        74065.87112417,  73377.85099095,  70641.88695488,  91851.61582327,
        89331.0718807 ,  72527.49640453,  76454.58789357,  87366.10736361,
        66375.85462869,  77536.48725694,  63076.79711062,  68805.66870093,
        63636.00328679,  73884.21750667,  67375.79515867,  97243.85379548,
        84467.28883801,  82210.0318811 ,  81397.79325501,  67380.05344154,
        77161.80093682,  94658.15826367,  87947.52563623,  67085.08947941,
        66647.31403528,  66756.57243721,  94252.433445  , 100745.97443423,
        83984.78179533,  64558.26153128,  69947.14609632,  68848.25312211,
        63422.57538702,  66637.49551442,  71371.93115519,  61899.67797046,
        98673.06118722,  

In [29]:
from sklearn.metrics import r2_score

In [30]:
r2_score(y_train,y_train_predicted)

0.5900887162191408

In [31]:
r2_score(y_test,y_test_predicted)

0.6707922937255979

# Predicting best Linear Model 

In [32]:
scores = []
for i in range(1000):
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=i)
    lm.fit(X_train,y_train)
    y_train_predicted = lm.predict(X_train)
    y_test_predicted = lm.predict(X_test)
    r2_score(y_test,y_test_predicted)
    scores.append(r2_score(y_test,y_test_predicted))

In [33]:
np.argmax(scores)

215

In [34]:
scores[np.argmax(scores)]

0.7245182902838088

# Predicting Using Best Model

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=215)
lm.fit(X_train,y_train)
y_train_predicted = lm.predict(X_train)
y_test_predicted = lm.predict(X_test)
r2_score(y_test,y_test_predicted)

0.7245182902838088

In [36]:
y_train_predicted

array([88389.23681763, 75050.63673   , 94462.74141378, ...,
       88042.26501146, 79126.76097278, 59592.38876051])

In [37]:
y_test_predicted

array([ 76027.57203976,  69354.91944067,  73804.94257211,  97643.49283679,
        77509.1309847 ,  61815.27769164,  63715.79004375,  72777.00344646,
        75694.13274137,  59464.58887384,  93972.09749249,  82201.85514358,
        82075.87724113,  75640.57643238,  71806.52945805,  72099.57537967,
        90695.4133868 ,  99291.8330289 ,  63115.67063125,  78832.76482149,
        69926.16676022,  75185.06290562,  86384.34450144,  84847.8204858 ,
        74613.96055292,  75901.62742585,  69945.43723169,  92804.45902917,
        68420.71932884,  69830.61202051,  94350.96314479,  65807.17118784,
        59530.85055651,  81465.66573246,  71200.25420888,  70956.38213307,
        69987.16119989,  67888.1639395 ,  71059.87559873,  58852.89668007,
        70638.10465469,  92265.8438536 ,  66509.72174162,  62160.73269788,
        73540.22725022,  66280.86698698,  70434.60893262,  97992.72068111,
        66821.0223214 , 105259.02153873,  90924.62038256,  74907.45416779,
        71318.4557253 ,  

In [38]:
y = lm.predict(X)

In [39]:
y

array([86236.55180338, 66340.57329466, 70350.22454165, ...,
       64250.47134553, 66262.19272318, 90983.8403971 ])

In [40]:
df['Predicted CTC'] = y

In [41]:
df.head()

S.No.  Previous CTC  Previous job changes  Graduation marks  Exp (Months)  \
0      1         55523                     3                66            19   
1      2         57081                     1                84            18   
2      3         60347                     2                52            28   
3      4         49010                     2                81            33   
4      5         57879                     4                74            32   

            CTC  College_Tier 1  College_Tier 2  Role_Manager  \
0  71406.576531               1               0             1   
1  68005.870631               0               1             0   
2  76764.020277               0               1             0   
3  82092.386880               0               0             0   
4  73878.097729               0               0             0   

   City type_Metro  Predicted CTC  
0                0   86236.551803  
1                1   66340.573295  
2                1   70350.224542  
3                1   67636.987833  
4                1   71046.451753

In [42]:
df.describe()

S.No.  Previous CTC  Previous job changes  Graduation marks  \
count  1338.000000   1338.000000           1338.000000       1338.000000   
mean    669.500000  55581.762332              2.525411         59.890882   
std     386.391641   6685.600553              1.123502         14.894696   
min       1.000000  36990.000000              1.000000         35.000000   
25%     335.250000  50547.000000              2.000000         47.000000   
50%     669.500000  55293.500000              3.000000         60.000000   
75%    1003.750000  60150.500000              4.000000         73.000000   
max    1338.000000  77911.000000              4.000000         85.000000   

       Exp (Months)            CTC  College_Tier 1  College_Tier 2  \
count   1338.000000    1338.000000     1338.000000     1338.000000   
mean      39.207025   75459.338993        0.485052        0.272048   
std       14.049960   12551.280263        0.499963        0.445181   
min       18.000000   53020.319026        0.000000        0.000000   
25%       27.000000   66905.070033        0.000000        0.000000   
50%       39.000000   73112.640487        0.000000        0.000000   
75%       51.000000   80747.178420        1.000000        1.000000   
max       64.000000  123416.994271        1.000000        1.000000   

       Role_Manager  City type_Metro  Predicted CTC  
count   1338.000000      1338.000000    1338.000000  
mean       0.204783         0.505232   75680.503396  
std        0.403694         0.500160    9650.075103  
min        0.000000         0.000000   57411.592447  
25%        0.000000         0.000000   68532.168381  
50%        0.000000         1.000000   73968.107439  
75%        0.000000         1.000000   80827.620298  
max        1.000000         1.000000  105259.021539

In [43]:
df.to_excel('Test_data_file.xlsx')